Одним из основных факторов, мотивирующим персонал компаний осуществлять эффективную трудовую деятельность, все еще остаётся размер оплаты труда (76%) (См.  Горохова, Е.Ю. Мотивация персонала 2014: Что движет россиянами при выборе места работы? [Электронный ресурс] URL: http://pro.rabota.ru/hr/ document/view/11875).  Разрыв между величиной оплаты труда от личных стараний, прикладываемых сотрудником, подрывает трудовое основание заработной платы и гасит инициативу и трудовые усилия человека. Как следствие, чтобы привлечь и удержать перспективных кандидатов нам необходимо предлагать конкурентную заработную плату, соответствующую их ожиданиям.

Объектом исследования является ежемесячный зарплатный доход сотрудников. Исследовательская проблема сформулирована в виде вопроса: каковы зарплатные ожидания кандидатов на вакантные позиции?

In [1]:
# Импортируем первую библиотеку для работы с данными Pandas
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.svm import SVR
from sklearn.ensemble import GradientBoostingRegressor

In [2]:
# Загрузим CSV-файл с данными (CSV-файл должен лежать рядом с исполняемым блокнотом)
df_hr = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

Существуют также методы для забора данных из Excel-файлов и БД

In [3]:
# Частично отрисуем этот датасет на экран
df_hr

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [4]:
# Проверим датасет на наличие пустых значений при помощи метода .info()

df_hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB


Мы проверили датасет на наличие пустых значений. В этом датасете их нет.

In [5]:
df_hr.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

Средний возраст сотрудников, работающих в организации 36,9 лет, максимальный - 60, минимальный - 18

In [6]:
# Pandas имеет еще один волшебный метод, который сразу считает матрицу корреляций по всему фрейму
df_hr.corr()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,0.010661,-0.001686,0.208034,NaN,-0.010145,0.010146,0.024287,0.029820,0.509604,...,0.053535,NaN,0.037510,0.680381,-0.019621,-0.021490,0.311309,0.212901,0.216513,0.202089
DailyRate,0.010661,1.000000,-0.004985,-0.016806,NaN,-0.050990,0.018355,0.023381,0.046135,0.002966,...,0.007846,NaN,0.042143,0.014515,0.002453,-0.037848,-0.034055,0.009932,-0.033229,-0.026363
DistanceFromHome,-0.001686,-0.004985,1.000000,0.021042,NaN,0.032916,-0.016075,0.031131,0.008783,0.005303,...,0.006557,NaN,0.044872,0.004628,-0.036942,-0.026556,0.009508,0.018845,0.010029,0.014406
Education,0.208034,-0.016806,0.021042,1.000000,NaN,0.042070,-0.027128,0.016775,0.042438,0.101589,...,-0.009118,NaN,0.018422,0.148280,-0.025100,0.009819,0.069114,0.060236,0.054254,0.069065
EmployeeCount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmployeeNumber,-0.010145,-0.050990,0.032916,0.042070,NaN,1.000000,0.017621,0.035179,-0.006888,-0.018519,...,-0.069861,NaN,0.062227,-0.014365,0.023603,0.010309,-0.011240,-0.008416,-0.009019,-0.009197
EnvironmentSatisfaction,0.010146,0.018355,-0.016075,-0.027128,NaN,0.017621,1.000000,-0.049857,-0.008278,0.001212,...,0.007665,NaN,0.003432,-0.002693,-0.019359,0.027627,0.001458,0.018007,0.016194,-0.004999
HourlyRate,0.024287,0.023381,0.031131,0.016775,NaN,0.035179,-0.049857,1.000000,0.042861,-0.027853,...,0.001330,NaN,0.050263,-0.002334,-0.008548,-0.004607,-0.019582,-0.024106,-0.026716,-0.020123
JobInvolvement,0.029820,0.046135,0.008783,0.042438,NaN,-0.006888,-0.008278,0.042861,1.000000,-0.012630,...,0.034297,NaN,0.021523,-0.005533,-0.015338,-0.014617,-0.021355,0.008717,-0.024184,0.025976
JobLevel,0.509604,0.002966,0.005303,0.101589,NaN,-0.018519,0.001212,-0.027853,-0.012630,1.000000,...,0.021642,NaN,0.013984,0.782208,-0.018191,0.037818,0.534739,0.389447,0.353885,0.375281
JobSatisfaction,-0.004892,0.030571,-0.003669,-0.011296,NaN,-0.046247,-0.006784,-0.071335,-0.021476,-0.001944,...,-0.012454,NaN,0.010690,-0.020185,-0.005779,-0.019459,-0.003803,-0.002305,-0.018214,-0.027656
MonthlyIncome,0.497855,0.007707,-0.017014,0.094961,NaN,-0.014829,-0.006259,-0.015794,-0.015271,0.950300,...,0.025873,NaN,0.005408,0.772893,-0.021736,0.030683,0.514285,0.363818,0.344978,0.344079
MonthlyRate,0.028051,-0.032182,0.027473,-0.026084,NaN,0.012648,0.037600,-0.015297,-0.016322,0.039563,...,-0.004085,NaN,-0.034323,0.026442,0.001467,0.007963,-0.023655,-0.012815,0.001567,-0.036746
NumCompaniesWorked,0.299635,0.038153,-0.029251,0.126317,NaN,-0.001251,0.012594,0.022157,0.015012,0.142501,...,0.052733,NaN,0.030075,0.237639,-0.066054,-0.008366,-0.118421,-0.090754,-0.036814,-0.110319
PercentSalaryHike,0.003634,0.022704,0.040235,-0.011111,NaN,-0.012944,-0.031701,-0.009062,-0.017205,-0.034730,...,-0.040490,NaN,0.007528,-0.020608,-0.005221,-0.003280,-0.035991,-0.001520,-0.022154,-0.011985
PerformanceRating,0.001904,0.000473,0.027110,-0.024539,NaN,-0.020359,-0.029548,-0.002172,-0.029071,-0.021222,...,-0.031351,NaN,0.003506,0.006744,-0.015579,0.002572,0.003435,0.034986,0.017896,0.022827
RelationshipSatisfaction,0.053535,0.007846,0.006557,-0.009118,NaN,-0.069861,0.007665,0.001330,0.034297,0.021642,...,1.000000,NaN,-0.045952,0.024054,0.002497,0.019604,0.019367,-0.015123,0.033493,-0.000867
StandardHours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockOptionLevel,0.037510,0.042143,0.044872,0.018422,NaN,0.062227,0.003432,0.050263,0.021523,0.013984,...,-0.045952,NaN,1.000000,0.010136,0.011274,0.004129,0.015058,0.050818,0.014352,0.024698
TotalWorkingYears,0.680381,0.014515,0.004628,0.148280,NaN,-0.014365,-0.002693,-0.002334,-0.005533,0.782208,...,0.024054,NaN,0.010136,1.000000,-0.035662,0.001008,0.628133,0.460365,0.404858,0.459188
TrainingTimesLastYear,-0.019621,0.002453,-0.036942,-0.025100,NaN,0.023603,-0.019359,-0.008548,-0.015338,-0.018191,...,0.002497,NaN,0.011274,-0.035662,1.000000,0.028072,0.003569,-0.005738,-0.002067,-0.004096
WorkLifeBalance,-0.021490,-0.037848,-0.026556,0.009819,NaN,0.010309,0.027627,-0.004607,-0.014617,0.037818,...,0.019604,NaN,0.004129,0.001008,0.028072,1.000000,0.012089,0.049856,0.008941,0.002759
YearsAtCompany,0.311309,-0.034055,0.009508,0.069114,NaN,-0.011240,0.001458,-0.019582,-0.021355,0.534739,...,0.019367,NaN,0.015058,0.628133,0.003569,0.012089,1.000000,0.758754,0.618409,0.769212
YearsInCurrentRole,0.212901,0.009932,0.018845,0.060236,NaN,-0.008416,0.018007,-0.024106,0.008717,0.389447,...,-0.015123,NaN,0.050818,0.460365,-0.005738,0.049856,0.758754,1.000000,0.548056,0.714365
YearsSinceLastPromotion,0.216513,-0.033229,0.010029,0.054254,NaN,-0.009019,0.016194,-0.026716,-0.024184,0.353885,...,0.033493,NaN,0.014352,0.404858,-0.002067,0.008941,0.618409,0.548056,1.000000,0.510224
YearsWithCurrManager,0.202089,-0.026363,0.014406,0.069065,NaN,-0.009197,-0.004999,-0.020123,0.025976,0.375281,...,-0.000867,NaN,0.024698,0.459188,-0.004096,0.002759,0.769212,0.714365,0.510224,1.000000

Довольно сильную положительрную связь мы наблюдаем между общим количеством лет работы в компании и количеством лет: в данной должности (0,758), после последнего продвижения (0,618) и работы с данным менеджером (0,769). Вероятно, что лояльность к компании формируется под влиянием удовлетворенности работы с менеджером и возможности карьерного роста. В то же время можно наблюдать положительную связь возраста работника с его уровнем должности в компании (0,509). Также очень высока связь между ежемесячным доходом и уровнем должности в компании (0,95)

In [ ]:
Инжиниринг

In [7]:
# Не учитывались категориальные столбцы, применим для них OneHotEncoding 

attriction_one_hot = pd.get_dummies(df_hr['Attrition'], prefix = 'attr', drop_first = True)
bussiness_travel_one_hot = pd.get_dummies(df_hr['BusinessTravel'], prefix = 'bus_tr')
gender_one_hot = pd.get_dummies(df_hr['Gender'], prefix = 'gend', drop_first = True)
marital_status_one_hot = pd.get_dummies(df_hr['MaritalStatus'], prefix = 'marital')
RelationshipSatisfaction_one_hot = pd.get_dummies(df_hr['RelationshipSatisfaction'], prefix = 'rel_sat')
Education_one_hot = pd.get_dummies(df_hr['Education'], prefix = 'edu')
EducationField_one_hot = pd.get_dummies(df_hr['EducationField'], prefix = 'edu_f')
Department_one_hot = pd.get_dummies(df_hr['Department'], prefix = 'dep')
JobRole_one_hot = pd.get_dummies(df_hr['JobRole'], prefix = 'job_role')

df_hr = df_hr.join([attriction_one_hot, 
            bussiness_travel_one_hot, 
            gender_one_hot, 
            marital_status_one_hot, 
            RelationshipSatisfaction_one_hot,
            Education_one_hot,
            EducationField_one_hot,
            Department_one_hot,
            JobRole_one_hot])

In [9]:
df_hr

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,dep_Sales,job_role_Healthcare Representative,job_role_Human Resources,job_role_Laboratory Technician,job_role_Manager,job_role_Manufacturing Director,job_role_Research Director,job_role_Research Scientist,job_role_Sales Executive,job_role_Sales Representative
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,0,0,0,0,0,0,0,1,0
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,0,0,0,0,0,0,0,1,0,0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,0,0,0,1,0,0,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,0,0,0,0,0,0,0,1,0,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,0,0,0,1,0,0,0,0,0,0
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,0,1,0,0,0,0,0,0,0,0
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,0,0,0,0,0,1,0,0,0,0
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,1,0,0,0,0,0,0,0,1,0
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,0,0,0,1,0,0,0,0,0,0

In [8]:
df_hr.corr()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,dep_Sales,job_role_Healthcare Representative,job_role_Human Resources,job_role_Laboratory Technician,job_role_Manager,job_role_Manufacturing Director,job_role_Research Director,job_role_Research Scientist,job_role_Sales Executive,job_role_Sales Representative
Age,1.000000,0.010661,-0.001686,0.208034,NaN,-0.010145,0.010146,0.024287,0.029820,0.509604,...,-0.027549,0.098825,-0.029856,-0.143176,0.294248,0.049726,0.185891,-0.146518,-0.002001,-0.175785
DailyRate,0.010661,1.000000,-0.004985,-0.016806,NaN,-0.050990,0.018355,0.023381,0.046135,0.002966,...,-0.003616,0.040141,-0.021156,-0.006728,-0.013224,-0.005302,-0.000021,-0.002624,-0.000513,0.005375
DistanceFromHome,-0.001686,-0.004985,1.000000,0.021042,NaN,0.032916,-0.016075,0.031131,0.008783,0.005303,...,0.014085,0.022916,-0.024089,0.012369,-0.039190,0.011848,-0.022351,-0.010986,0.030761,-0.015994
Education,0.208034,-0.016806,0.021042,1.000000,NaN,0.042070,-0.027128,0.016775,0.042438,0.101589,...,0.014215,0.024270,-0.005295,-0.063566,0.028453,-0.005290,0.049694,0.000709,0.053398,-0.091465
EmployeeCount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
job_role_Manufacturing Director,0.049726,-0.005302,0.011848,-0.005290,NaN,-0.014350,0.059178,-0.014394,-0.021939,0.114896,...,-0.218320,-0.103472,-0.063349,-0.152987,-0.090330,1.000000,-0.079362,-0.164700,-0.176592,-0.080924
job_role_Research Director,0.185891,-0.000021,-0.022351,0.049694,NaN,-0.013983,-0.048689,-0.025128,0.015200,0.414319,...,-0.158327,-0.075038,-0.045941,-0.110947,-0.065508,-0.079362,1.000000,-0.119442,-0.128066,-0.058687
job_role_Research Scientist,-0.146518,-0.002624,-0.010986,0.000709,NaN,-0.017686,0.001940,0.020034,0.047604,-0.387788,...,-0.328576,-0.155727,-0.095342,-0.230248,-0.135949,-0.164700,-0.119442,1.000000,-0.265775,-0.121792
job_role_Sales Executive,-0.002001,-0.000513,0.030761,0.053398,NaN,0.023263,-0.024421,-0.011886,-0.011413,0.127490,...,0.808869,-0.166971,-0.102226,-0.246873,-0.145765,-0.176592,-0.128066,-0.265775,1.000000,-0.130586
job_role_Sales Representative,-0.175785,0.005375,-0.015994,-0.091465,NaN,0.006255,0.002949,-0.018703,-0.027282,-0.216559,...,0.370667,-0.076515,-0.046845,-0.113130,-0.066797,-0.080924,-0.058687,-0.121792,-0.130586,1.000000

In [70]:
#Самые важные признаки, влияющие на месячный доход
most_important_f = ['Age', 
 'JobLevel', 
 'NumCompaniesWorked', 
 'TotalWorkingYears', 
 'attr_Yes', 
 'job_role_Laboratory Technician', 
 'job_role_Manager',
 'job_role_Research Director',
 'job_role_Research Scientist',
 'job_role_Sales Representative']

# Подготовка данных для обучения

In [71]:
most_important_f.extend(['job_role_Sales Executive', 
                                        'job_role_Human Resources',
                                        'job_role_Healthcare Representative',
                                        'bus_tr_Non-Travel',
                                        'bus_tr_Travel_Frequently',
                                        'bus_tr_Travel_Rarely',
                                        'gend_Male',
                                        'marital_Divorced',
                                        'marital_Married',
                                        'marital_Single',
                                        'rel_sat_1',
                                        'rel_sat_2',
                                        'rel_sat_3',
                                        'rel_sat_4',
                                        'edu_1',
                                        'edu_2',
                                        'edu_3',
                                        'edu_4',
                                        'edu_5',
                                        'edu_f_Human Resources',
                                        'edu_f_Life Sciences',
                                        'edu_f_Marketing',
                                        'edu_f_Medical',
                                        'edu_f_Other',
                                        'edu_f_Technical Degree'
                                       ])

In [81]:
df_hr.shape

(1470, 70)

In [84]:
X_train = df_hr.loc[:1200, most_important_f]
Y_train = df_hr.loc[:1200, 'MonthlyIncome']

In [85]:
X_test = df_hr.loc[1200:, most_important_f]
Y_test = df_hr.loc[1200:, 'MonthlyIncome']

# Обучение

Построение модели линейной регресси

In [86]:
lin_mod = LinearRegression()

In [87]:
lin_mod.fit(X_train, Y_train)

LinearRegression()

In [90]:
for pred_, true_ in zip(lin_mod.predict(X_test), Y_test):
    print(pred_, true_)

2797.8877034424204 3195
2596.9020730471725 3989
2346.0978386256797 3306
8992.191765259893 7005
3008.068727183369 2655
2220.0594180511403 1393
2456.7650122445616 2570
2733.8260134803654 3537
5644.631212383888 3986
9286.476686923312 10883
2912.529852872948 2028
5738.050834201647 9525
2801.7366297488957 2929
2426.7312619854197 2275
8786.979739197439 7879
2616.5901009010786 4930
5898.040860509814 7847
2628.166785348811 4401
8749.054450651285 9241
2720.5269109021438 2974
5722.061592789851 4502
9699.28583645483 10748
3210.275183345142 1555
12450.055547698434 12936
2448.7869719300934 2305
15982.728969876765 16704
2891.202248296797 3433
2521.7971379780024 3477
6033.682707170372 6430
6132.857014803433 6516
2646.334295625972 3907
6526.451903996238 5562
6346.495263702863 6883
3069.6072853171218 2862
5638.346198178968 4978
8848.749898983198 10368
6172.790437997493 6134
5901.969624662431 6735
2439.502859486842 3295
5976.3851055778205 5238
5310.889113041134 6472
8858.023706660122 9610
18887.30530022898 19833
8583.96030254998 9756
2733.3958698352026 4968
2773.5069808597627 2145
3157.820680359691 2180
5940.941841480072 8346
2561.673754042109 3445
2368.698767923004 2760
6169.385933749934 6294
8654.330287341127 7140
2582.4084885993248 2932
5965.947656672026 5147
5804.421090912995 4507
8780.364824312486 8564
2454.0985219790964 2468
8857.17832476216 8161
2396.8052537773715 2109
6278.309536102482 5294
2861.80775135875 2718
6484.707870751955 5811
2873.463551982467 2437
2564.416978739533 2766
19663.388045705742 19038
5591.811084148552 3055
2395.8242987540693 2289
6106.224847691617 4001
12067.501307586568 12965
3033.6426215510137 3539
5433.433118172203 6029
2553.39962590417 2679
2184.9077552670587 3702
2504.3141540208903 2398
6050.605357242166 5468
13084.28435168583 13116
5591.355012032245 4189
19124.12729231426 19328
9238.23970712024 8321
2532.4889471301967 2342
6116.802405770972 4071
5967.910092224829 5813
3141.646516451434 3143
2717.6798754645906 2044
13030.8875466296 13464
5530.81278748085 7991
2328.245087254116 3377
6245.245966753301 5538
5919.600553707856 5762
3293.076255982264 2592
5721.3928461798805 5346
5950.745877357214 4213
5748.276752727811 4127
2596.7913491135 2438
6089.910677504249 6870
9402.647648200755 10447
8612.798195875166 9667
2803.7154849217777 2148
6099.5347574936795 8926
6091.420048734309 6513
5967.592486864686 6799
16757.312944443212 16291
2516.790750972825 2705
9566.372162447 10333
6256.350586101151 4448
5705.2973121581645 6854
8671.481219145799 9637
2495.797024611776 3591
5890.887923182165 5405
5611.649311581691 4684
16281.423650563094 15787
2166.3783305427078 1514
2834.084788802763 2956
3057.8388797481 2335
5775.782033037382 5154
5735.452393701773 6962
5874.02487692707 5675
2272.2848034228596 2379
2968.2732740574606 3812
5813.101121496766 4648
2830.317441710915 2936
2449.4345466755353 2105
8658.568197914465 8578
2454.959465229515 2706
6371.839822753289 6384
2552.512897786924 3968
6023.671140471961 9907
12121.408694357471 13225
5485.105071140892 3540
2820.204685947045 2804
18906.58525623848 19392
19375.335462332325 19665
2298.9016433404367 2439
9010.311394347122 7314
2678.5856185924263 4774
5425.962389755774 3902
3416.184900348569 2662
2162.641575700267 2856
2329.8348394331383 1081
2558.0119113422124 2472
5885.294250236038 5673
5383.712308306059 4197
8710.401885394516 9713
2765.475782744364 2062
6012.11532658985 4284
5337.879550446417 4788
5662.336418915543 5906
6151.826692633869 3886
16126.921082482506 16823
2257.5959349013833 2933
5605.9453424742005 6500
16187.912229251393 17174
6128.255420030921 5033
2658.4190243281646 2307
2242.325977307122 2587
6073.4549978034065 5507
6251.420941246574 4393
13379.445668455144 13348
5531.554446695733 6583
6066.191036512176 8103
2343.993636848072 3978
2553.2767263347973 2544
6225.0308513503205 5399
5986.924623413323 5487
5771.007212733217 6834
2342.0537187244377 1091
5859.071474668214 5736
2820.6362250379566 2226
5902.1621454181495 5747
5612.711202987302 9854
5979.889669916678 5467
5557.53759205703 5380
5773.386272168038 5151
6000.631194300839 2133
16563.5888856875 17875
2482.038142671255 2432
2619.034074974138 4771
19469.113795078636 19161
6228.632964311127 5087
2828.6358764908186 2863
5732.293177437685 5561
2489.2886076745085 2144
2187.8927227308855 3065
2371.7409839310185 2810
8893.287447478613 9888
8660.270386796814 8628
2536.9563946895655 2867
5930.300545959487 5373
5852.629896283571 6667
5684.118990217299 5003
2610.76116742754 2367
3108.9670257141934 2858
5858.83448098387 5204
5797.289378024129 4105
5883.766348124564 9679
6202.539386180637 5617
9004.266369330719 10448
5363.913443475328 2897
5954.344591488225 5968
8942.407796540449 7510
2916.3682431026355 2991
19803.15981435219 19636
2319.3006843342437 1129
11966.886667995374 13341
5737.63294274676 4332
12929.177793672367 11031
5707.777748076769 4440
5680.5038393923605 4617
2289.402477564445 2647
5410.262379471139 6323
6119.12164218906 5677
3156.5673464899733 2187
2739.1871477593577 3748
2755.90906924187 3977
9582.485844295083 8633
1976.3375265563768 2008
6202.640102877963 4440
2282.940147870105 3067
5956.037812868159 5321
5595.223961170653 5410
2929.8150375991772 2782
12924.200128583558 11957
2585.67835726123 2660
2342.814792929701 3375
5545.595703007071 5098
5831.787329471338 4878
2411.2705718764937 2837
2750.7409172593566 2406
2361.8919412485975 2269
6111.310644789479 4108
13249.436999231824 13206
8985.163327503562 10422
13051.570939929015 13744
5429.830989712817 4907
2785.869001537759 3482
2668.0922984809454 2436
2402.5539448489217 2380
18860.355267854415 19431
2408.702791255409 1790
8692.585834700796 7644
6116.569600891593 5131
5987.576827224178 6306
2742.371000181303 4787
19121.518916174005 18880
2918.632865646495 2339
11984.628589199378 13570
5849.125382180663 6712
6032.1496466529325 5406
6169.218546964333 8938
2556.3161116597253 2439
8477.140157990896 8837
5785.416997498909 5343
6075.756436414928 6728
5818.800177012076 6652
5816.902774348888 4850
2657.467855750925 2809
6147.082805243903 5689
3255.8249145335503 2001
2445.8101839898927 2977
5286.650387243487 4025
2443.5740193748693 3785
9330.32676237483 10854
12121.774009891898 12031
5777.574225549569 9936
2235.7126345619945 2966
5773.500642870299 2571
8994.658433703004 9991
5828.836158538549 6142
6281.853661258828 5390
5250.796990875433 4404

Построение модели опорных векторов

In [101]:
svr_reg = SVR()

In [102]:
svr_reg.fit(X_train, Y_train)

SVR()

In [103]:
for pred_, true_ in zip(svr_reg.predict(X_test), Y_test):
    print(pred_, true_)

4938.027421114012 3195
4849.381382747037 3989
4910.584036509703 3306
4985.638498030098 7005
5008.945177375279 2655
4858.080299689833 1393
4865.019420779571 2570
4974.415192092241 3537
4935.568686377708 3986
5033.276210412779 10883
4924.973338530659 2028
4899.7294980156685 9525
4907.212831223623 2929
4842.305244779521 2275
4944.171481804308 7879
4890.1868211557085 4930
4944.682100240818 7847
4851.584457490885 4401
4937.882046624128 9241
4888.822296236607 2974
4955.811060090056 4502
5029.039486679197 10748
4837.7000313149 1555
5036.149074827019 12936
4848.671619689146 2305
5011.768525899688 16704
4902.091396251386 3433
4876.098463507027 3477
4939.063871976334 6430
4977.077352682071 6516
4855.695693510493 3907
5005.533517373168 5562
4951.34258476414 6883
4892.192393499495 2862
4931.647127504236 4978
4974.823165294363 10368
4951.520080470572 6134
4903.461298888209 6735
4842.152040811961 3295
4892.2547047952285 5238
4922.940318247821 6472
4902.87536299198 9610
4994.8656304339875 19833
4949.298984842477 9756
4891.911151553189 4968
4844.186699447033 2145
4875.607210317228 2180
4877.347111240535 8346
4863.352830049889 3445
4852.927240393535 2760
4894.034262115812 6294
4905.596293308565 7140
4886.456640585192 2932
4924.596936404469 5147
4957.108807435088 4507
4911.463766375266 8564
4919.312234559154 2468
4898.724528093409 8161
4849.191184250533 2109
4894.350625601156 5294
4910.606836317331 2718
4953.183735006848 5811
4926.12714862131 2437
4926.910555658633 2766
5068.525764974137 19038
4911.702051016555 3055
4909.234427752165 2289
4935.901461394659 4001
5054.445209395039 12965
4942.967845678192 3539
4890.125291735029 6029
4832.9392441372365 2679
4897.356041126368 3702
4834.138488128469 2398
4913.220746338942 5468
5000.091371581604 13116
4894.815599216821 4189
5030.465985516212 19328
4947.93650415703 8321
4925.936619673461 2342
4970.229836279962 4071
4912.459072686371 5813
4927.47505086228 3143
4861.937034399707 2044
4927.268617022881 13464
4938.251218437111 7991
4916.7941484447465 3377
4942.609804949385 5538
4940.3210445455115 5762
4941.916077696679 2592
4915.039295494327 5346
4920.3721057795765 4213
4913.154138802748 4127
4928.581071064343 2438
4943.085532636027 6870
5005.678262695439 10447
4894.277589807145 9667
4860.62662529101 2148
4973.6432558735905 8926
4945.198274608933 6513
4908.654982095106 6799
5069.875240561455 16291
4890.282467859327 2705
5045.217082833648 10333
4960.8588780352775 4448
5002.186198061194 6854
4893.6914976957105 9637
4853.781836021081 3591
4979.483086095739 5405
4857.622112314065 4684
5046.375094089286 15787
4827.506738757939 1514
4858.814820349056 2956
4862.300226112928 2335
4953.85888782525 5154
4945.223620218427 6962
4928.668399488081 5675
4863.220425808835 2379
4893.8418509783705 3812
4876.163626769943 4648
4940.330086255718 2936
4943.902623650551 2105
4968.846426565897 8578
4854.15798997925 2706
4899.132322668525 6384
4929.962315806165 3968
4889.099679621201 9907
5032.502146885246 13225
4878.343481085821 3540
4849.352750219733 2804
5008.021309919303 19392
5051.890306829048 19665
4849.138118496644 2439
4980.491969295615 7314
4872.239499803957 4774
4916.209596402799 3902
5026.197169374477 2662
4846.614340624029 2856
4852.017925569097 1081
4834.0498994801155 2472
4916.619148538812 5673
4896.843227581452 4197
4904.847118502336 9713
4894.661000116303 2062
4955.263477103843 4284
4881.988930158674 4788
4951.801825365955 5906
4916.36611965697 3886
4999.357035020809 16823
4841.645742120508 2933
4878.28526103617 6500
5034.397639052162 17174
4949.06887918859 5033
4882.039457622089 2307
4961.11080278741 2587
4928.045855809597 5507
4960.83040914715 4393
4988.057307291494 13348
4887.508768625921 6583
4904.22455157852 8103
4871.522742931115 3978
4869.339621478836 2544
4964.5871860020925 5399
4904.829764438418 5487
4872.236098107016 6834
4849.255863838737 1091
4931.254470687759 5736
4863.471373477333 2226
4941.039881149225 5747
4868.501395566426 9854
4993.716530746496 5467
4968.272858334077 5380
4928.58479333371 5151
4978.7029039742765 2133
5062.667330473203 17875
4890.0397223542905 2432
4923.724711490289 4771
5050.807904083607 19161
4963.926240017321 5087
4844.204872096018 2863
4891.635746500056 5561
4861.941696219824 2144
4867.122034389513 3065
4889.614754009527 2810
4931.457292480059 9888
4904.488467092212 8628
4869.270565427909 2867
4870.366469777277 5373
4897.775291906234 6667
4896.817458921309 5003
4868.314738442904 2367
4979.138373244034 2858
4912.657825260699 5204
4869.175193643215 4105
4894.613427484279 9679
4897.259107285774 5617
5006.360755777751 10448
4977.007336002867 2897
4899.463869267215 5968
4945.710476782464 7510
4907.193846041665 2991
5070.006758536128 19636
4855.035708329204 1129
4989.5507366543225 13341
4994.202420471253 4332
4915.494974621057 11031
4978.174185934724 4440
4848.909682112747 4617
4849.506763931348 2647
4932.3629793833325 6323
4961.476614320338 5677
4859.601655781722 2187
4902.67253510845 3748
4865.065797462358 3977
5034.323654049122 8633
4861.495658365977 2008
4957.298999376185 4440
4862.712326246847 3067
4924.996087956029 5321
4937.449919049538 5410
4947.276315302975 2782
4981.464104214772 11957
4889.178586511212 2660
4843.69883172261 3375
4912.198367961059 5098
4904.30227122866 4878
4879.531794780151 2837
4924.28320399699 2406
4866.024881210491 2269
4974.704987818962 4108
4981.049157293601 13206
4923.6033574943 10422
4954.676296565585 13744
4859.219619959029 4907
5005.433714990363 3482
4928.3269472546735 2436
4835.795489700824 2380
4991.436567151066 19431
4835.920869821553 1790
4917.239232333481 7644
4962.949760001619 5131
5000.473745195354 6306
4866.244473590201 4787
5017.5712368392715 18880
5005.77894056849 2339
4997.155513288281 13570
4898.238302815673 6712
4944.166414827087 5406
4959.392776311982 8938
4870.31544205383 2439
4908.182634572718 8837
4924.691157499144 5343
4982.530921546542 6728
4907.493025575606 6652
4944.852108992825 4850
4921.005148430974 2809
4912.554520742918 5689
4986.1498674585655 2001
4881.119266996592 2977
4891.12960920345 4025
4865.0186676611465 3785
5022.2065398599225 10854
4989.536149654397 12031
4896.638907844801 9936
4856.374788330147 2966
4956.124134547328 2571
4925.682261352889 9991
4864.507707060701 6142
5003.488091502808 5390
4888.143862784937 4404

In [ ]:
Регрессия с усилением градиента

In [104]:
gb_reg = GradientBoostingRegressor()

In [106]:
gb_reg.fit(X_train, Y_train)

GradientBoostingRegressor()

In [107]:
for pred_, true_ in zip(gb_reg.predict(X_test), Y_test):
    print(pred_, true_)

3069.8459551034416 3195
2902.9214406463043 3989
3033.5410222162404 3306
8440.337296904092 7005
1693.4011872644994 2655
2373.0613679817066 1393
3069.5014184931824 2570
2920.9223498842234 3537
4513.762124053839 3986
9941.028728722713 10883
2909.632064627726 2028
5907.881270308105 9525
2952.7583176755975 2929
2749.7017860757574 2275
8513.194133752902 7879
3171.2241068238714 4930
5848.379822036517 7847
2737.957667527283 4401
8569.331544820887 9241
3241.024716607945 2974
4235.5349109025765 4502
10173.51689049768 10748
2604.1253618254864 1555
13649.231182249323 12936
2936.1789582538627 2305
16321.72574869079 16704
3031.907032229431 3433
3131.6794977842546 3477
5666.552756726066 6430
5595.317910616968 6516
3120.189060025933 3907
5684.862491284255 5562
5778.754444916693 6883
2934.926847033275 2862
4929.007716505069 4978
9860.846668038575 10368
5932.376834440172 6134
5813.4634522143215 6735
2840.9762009118967 3295
5569.484176705225 5238
4676.409558657366 6472
8789.476804747368 9610
19024.63915023181 19833
8600.274251819752 9756
2740.9347082625263 4968
2899.9672988971392 2145
3267.431216160467 2180
6074.577234863772 8346
2953.5918013263736 3445
2647.1096113516714 2760
5737.636974383865 6294
8639.362869078983 7140
3139.1567874002917 2932
6069.084170707834 5147
5840.031660104285 4507
8532.011090453183 8564
2998.3022053696677 2468
8665.528240335321 8161
2241.591993921255 2109
5946.196444284862 5294
2928.960925542851 2718
6055.317686563421 5811
2967.193252243904 2437
3059.6951110827167 2766
19204.739294314448 19038
4799.989842571946 3055
2896.0464562368043 2289
6001.657657142687 4001
14441.846630671533 12965
3066.6255412600353 3539
5893.0175632423025 6029
2270.061430527534 2679
2782.8783921849495 3702
2324.450777535849 2398
5929.756010106544 5468
12162.995329042233 13116
4759.781813332568 4189
19213.781531164517 19328
9949.252030694082 8321
2950.9782546808415 2342
5536.3657386755895 4071
5950.55734417806 5813
3104.0453915704043 3143
2840.792456162994 2044
12320.10747044793 13464
5831.581858807161 7991
3003.198255528588 3377
5832.490897617703 5538
5603.429730178872 5762
3188.455683972452 2592
4761.319070553952 5346
5514.083510190307 4213
5966.767385394565 4127
2869.49230193812 2438
5710.3432610374675 6870
9827.991654714351 10447
8725.799713670845 9667
3115.882315627296 2148
5775.932182988404 8926
5880.721286698258 6513
5966.057539403878 6799
15634.008003239955 16291
3145.941291774553 2705
9886.777562393008 10333
5892.45905241122 4448
5089.1294516242115 6854
8704.90068585632 9637
2742.953242354597 3591
3937.250014298171 5405
4600.740576696688 4684
16085.770955323862 15787
1717.8128246497538 1514
3148.9620019255585 2956
3023.907650206116 2335
5783.215446364005 5154
4934.548707494433 6962
6019.742760925367 5675
3050.67794340464 2379
3053.695166374351 3812
4892.501233231345 4648
2837.3726350948455 2936
2953.8840933002784 2105
8670.214982707725 8578
2766.1266610521475 2706
5751.2110242251965 6384
2980.0464608197813 3968
5982.96142767403 9907
13648.818240361934 13225
4886.21140957639 3540
2391.728995226436 2804
19107.741461228394 19392
19088.151693751286 19665
2162.580612409133 2439
9828.82153297832 7314
2767.718317404897 4774
4929.4065763207955 3902
3492.501030389009 2662
2096.1137271986795 2856
2235.2480939966827 1081
2206.9737988073975 2472
5786.91928974372 5673
4704.798310434566 4197
8665.528240335321 9713
2972.7997473913665 2062
5177.271655133949 4284
4486.035938859412 4788
5358.980831572349 5906
5696.030868144187 3886
16358.921995517756 16823
2188.912017643375 2933
5705.2243350215085 6500
16399.510383248573 17174
5746.482678093936 5033
2822.4469402164314 2307
2686.6212001939753 2587
6057.5945826261905 5507
5978.774300649577 4393
13475.057264213003 13348
5795.454554338754 6583
6097.149607576819 8103
3017.7673421717095 3978
3078.268542507463 2544
5885.058407381819 5399
5857.379321928101 5487
6009.062688441354 6834
2138.028282517804 1091
5839.268954049696 5736
3041.1745435309344 2226
5130.238043126818 5747
5968.134477917648 9854
4900.4839162361395 5467
5895.389676427473 5380
5452.854230437238 5151
4890.5205587201235 2133
15822.032565640055 17875
2907.206226274614 2432
2886.962947593913 4771
19223.516467965383 19161
5998.9264425071015 5087
2480.930499316222 2863
6052.561862911931 5561
2681.5367173225554 2144
2686.818136864041 3065
2911.714044919259 2810
9865.67375891637 9888
8623.468934713563 8628
3002.9092613039834 2867
5867.834993363471 5373
5764.259138261616 6667
5184.014528582163 5003
3044.255633542955 2367
2363.744704398224 2858
5880.097311993679 5204
5913.5488666151505 4105
5542.351120749126 9679
6031.572085826296 5617
9671.458601083386 10448
5222.798676258504 2897
5804.415831183934 5968
8613.736466467975 7510
3185.037798739009 2991
19557.461988694995 19636
2337.9794400008336 1129
13645.578158290655 13341
4842.420344474573 4332
13336.308968355734 11031
5508.639446581151 4440
4711.504862702422 4617
3052.348301751733 2647
4643.002206358435 6323
5965.461893105733 5677
3403.8601453595425 2187
2925.865548827442 3748
4038.664797177998 3977
9862.2269159233 8633
2282.324587604023 2008
6142.071548796941 4440
2894.4066028366597 3067
5572.631842444063 5321
5044.116907609924 5410
3111.342774358838 2782
12925.642908796304 11957
2994.5819459504332 2660
2707.263041725413 3375
4960.179198877606 5098
5638.939635688755 4878
3093.103605520098 2837
3115.9259583551166 2406
2712.1478033439994 2269
5313.696012124765 4108
13343.0118562605 13206
9842.859594159412 10422
13107.464100535426 13744
5678.596973635704 4907
2100.772009822749 3482
2973.724725045829 2436
2495.3894885863015 2380
19052.699895249167 19431
2200.857178326956 1790
8553.00890252918 7644
5681.697712758243 5131
5817.356635611633 6306
2827.4930711044367 4787
19136.850932140154 18880
2795.399964111442 2339
14293.022413408062 13570
5880.097311993679 6712
5954.011789715265 5406
5998.9435582723945 8938
2842.627143073623 2439
8597.162806269433 8837
5796.097154982808 5343
6023.735937792993 6728
5861.506627163371 6652
5859.6795330941995 4850
2906.0721327453457 2809
5790.734720835943 5689
3167.957320709056 2001
2863.281354594954 2977
4567.326983762043 4025
2758.544364499628 3785
9796.13132349099 10854
13601.653217709398 12031
5467.879257614647 9936
2724.316799323468 2966
4452.606160214311 2571
8799.621276758651 9991
5639.149683775194 6142
6100.9098205969 5390
4840.6392816446005 4404

Посчитаем среднее квадратичное ошибку

In [111]:
# Для метода опорных векторов
res = 0
for pred_, true_ in zip(svr_reg.predict(X_test), Y_test):
    res += (pred_ - true_) ** 2
    
res /= Y_test.shape[0]

res

18068088.485613115

In [109]:
# Для линейной регрессии
res = 0
for pred_, true_ in zip(lin_mod.predict(X_test), Y_test):
    res += (pred_ - true_) ** 2
    
res /= Y_test.shape[0]

res

1393426.1142288567

In [110]:
# Для GradientBoostingRegressor()
res = 0
for pred_, true_ in zip(gb_reg.predict(X_test), Y_test):
    res += (pred_ - true_) ** 2
    
res /= Y_test.shape[0]

res

1188643.0439660943

In [ ]:
Выводы:
    Чтобы предсказать конкурентную заработную плату кандидатов, которая могла бы удовлетворить их ожиданиям, были построены три модели (метод опорных векторов, линейной регресии, градиентов). Самая эффективная модель - GradientBoostingRegressor, которая сторится на основании данных Age, 
JobLevel, TotalWorkingYears, attr_Yes, job_role_Laboratory Technician, job_role_Manager, job_role_Research Director, job_role_Research Scientist, job_role_Sales Representative, выбранных по принципу факторов имеющих самую сильную коррелляцию с ежемесячных доходов.